### ISSUE TITLE
The models with Reveal

### ISSUE THREAD

**Issue by foresta-yang** [biringaChi/biringaChi#1]
Dear biringaChi,
In Reveal https://github.com/VulDetProject/ReVeal?tab=readme-ov-file, I can't find  models with "bash get_models.sh", either with the link which youshare in the issues, such as [CStyle-V](https://github.com/biringaChi/CStyle-V), (https://github.com/biringaChi/vRAG), are unavailable, I can't find the repository in your personal pages, Would you share the models with me? thank you!

**Comment by biringaChi** [comment]
Hello, I don't have access to the models, just the dataset.
